In [1]:
import torch

### Gradient

In [6]:
a = torch.tensor([1.,2.,3.], requires_grad=True)
b = 2 * torch.dot(a, a)
b

tensor(28., grad_fn=<MulBackward0>)

In [4]:
b.backward()
a.grad

tensor([ 4.,  8., 12.])

In [5]:
a.grad == 4 * a

tensor([True, True, True])

In [10]:
x = torch.ones((1,3), requires_grad=True)
y = x * x 
u = y.detach()
u

tensor([[1., 1., 1.]])

In [11]:
z = u * x
z.sum().backward()
x.grad == u

tensor([[True, True, True]])

In [12]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([[True, True, True]])